<?php

/**
 * @file
 *
 * Show unused and disabled forms for the site.
 */

/**
 * Implements hook_menu().
 */
function cu_unused_forms_menu() {
  $items = array();
  $items['admin/reports/forms/unused'] = array(
    'title' => 'Unused Forms',
    'description' => 'A list of Forms that are not being displayed on this site.',
    'page callback' => 'cu_unused_forms_list',
    'access arguments' => array('view unused forms'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/forms/unused/main'] = array(
    'title' => 'Have not been used recently',
    'description' => 'A list of Forms that are not being displayed on this site.',
    'page callback' => 'cu_unused_forms_list',
    'access arguments' => array('view unused forms'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/reports/forms/unused/remove'] = array(
    'page callback' => 'cu_unused_forms_list_remove',
    'page arguments' => array(4),
    'access arguments' => array('view unused forms'),
    'title' => 'Can be removed',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1000,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function cu_unused_forms_permission() {
  return array(
    'view unused forms' => array(
      'title' => 'View Unused forms',
      'description' => 'View a list of unused/unreferenced forms.',
    ),
  );
}

function _submissions_from_form($nid) {
  $submission_info = [];
  $forms_submissions_query = db_query('SELECT * FROM webform_submissions WHERE nid = :nid', array(':nid' => $nid));
  $forms_submissions = $forms_submissions_query->fetchAll();

  foreach($forms_submissions as $submission) {
    $submitted[] = $submission->submitted;
  }

  $submission_info['last_submission'] = max($submitted);
  $submission_info['total_submissions'] = count($submitted);

  return $submission_info;
}

function _webform_records() {
  $forms_count_query = db_query('SELECT * FROM webform');
  $forms_count = $forms_count_query->fetchAll();

  // Return all form nids (webform) to $form_nids.
  $form_nids = array();
  foreach ($forms_count as $form) {
    $form_nids[] = $form->nid;
  }

  return $form_nids;
}

/**
 * Page callback for /admin/reports/forms/unused.
 */
function cu_unused_forms_list() {
  drupal_add_css(drupal_get_path('module', 'cu_inactive_users') . '/css/cu-inactive-users.css', array('group' => CSS_DEFAULT));
  $output = [];

  $list = array();

  // Set the default time we want to check access for.
  $time = isset($_GET['time']) ? check_plain($_GET['time']) : 60*60*24*60;

  // Build a readable date we are checking against
  $now = time();
  $since = $now - $time;
  $nice_since = date('F j, Y', $since);

  // Add some links to allow user to filter by date.
  $time_filters = array();
  $time_options = array(
    '7 Days' => (60*60*24*7),
    '30 Days' => (60*60*24*30),
    '90 Days' => (60*60*24*90),
    '1 Year' => (60*60*24*365),
  );
  $path = current_path();
  global $base_url;
  // If a time is already set, add a default/reset link.
  if ($_GET['time']) {
    $time_filters[] = "<a href=\"$base_url/$path\">Default (60 Days)</a>";
  }
  // Loop through time filter options.
  foreach ($time_options as $label => $interval) {
    if ($_GET['time'] == $interval) {
      $class = 'active-time-filter';
    }
    else {
      $class = '';
    }
    $time_filters[] = "<a href=\"$base_url/$path?time=$interval\" class=\"$class\">$label</a>";
  }

  $form_nids = _webform_records();
  $forms[] = node_load_multiple($form_nids);

  foreach ($forms as $form) {
    // If time matches current filtered time.
    foreach ($form as $key => $stale_form) {
      $name = l($stale_form->title, 'node/' . $stale_form->nid . '/edit');
      $author = $stale_form->name;
      $submissions_info = _submissions_from_form($stale_form->nid);
      $webform_updated_date = date('F j, Y', $stale_form->changed);
      $last_submission_date = date('F j, Y', $submissions_info['last_submission']);
      $last_submission = (!empty($submissions_info['last_submission'])) ? $last_submission_date : 'has no submissions';
      $total_submissions = (!empty($submissions_info['total_submissions'])) ? $submissions_info['total_submissions'] : 'has no submissions';

      if ($stale_form->changed < $since || $submissions_info['last_submission'] < $since) {
        $list[$stale_form->nid] = "$name<br><ul><li>Webform last updated: $webform_updated_date</li><li>Last submission: $last_submission</li><li>Total submissions: $total_submissions</li><li><small>Author: $author</small></li></ul>";
      }
    }
  }

  $output['stale_forms']['#prefix'] = '<h2>Have not been used recently</h2>';
  $output['stale_forms']['description']['#markup'] = "<p>The webforms listed below have not been updated or had submissions since $nice_since.</p>";
  $output['stale_forms']['filters']['#prefix'] = '<div class="inactive-time-filter">Use the links below to change the date checked.';
  $output['stale_forms']['filters']['#suffix'] = '</div>';
  $output['stale_forms']['filters']['#markup'] = theme('item_list', array('items' => $time_filters, 'attributes' => array('class' => array('inactive-users-time-filters'))));
  $output['stale_forms']['list']['#markup'] = theme('item_list', array('items' => $list, 'attributes' => array('class' => array('bullet-list'))));


  return $output;
}

/**
 * Menu callback /admin/reports/forms/unused/remove
 */
function cu_unused_forms_list_remove() {
  $output = [];
  $list = [];
  $year_ago = time() - 60*60*24*365;
  $year_ago_date = date('F j, Y', $year_ago);

  $form_nids = _webform_records();
  foreach ($form_nids as $form) {
    $form = node_load($form);
    $submission_info = _submissions_from_form($form->nid);

    $name = l($form->title, 'node/' . $form->nid . '/edit');
    if ($form->changed < $year_ago && ($submission_info['last_submission'] < $year_ago || $submission_info['last_submission'] == NULL)) {
      $list[] = $name;
    }
  }

  dpm(count($list));
  $list = (count($list) > 0) ? $list : $list = array('empty' => t('No forms meet the criteria to be removed.'));

  $output['remove_forms']['#prefix'] = '<h2>Can be removed</h2>';
  $output['remove_forms']['description']['#markup'] = "<p>The webforms listed below have not been updated or had submissions since $year_ago_date.</p>";
  $output['remove_forms']['list']['#markup'] = theme('item_list', array('items' => $list, 'attributes' => array('class' => array('bullet-list'))));

  return $output;
}
