<?php

/**
 * @file
 *
 * Show unused and disabled forms for the site.
 */

/**
 * Implements hook_menu().
 */
function cu_unused_forms_menu() {
  $items = array();
  $items['admin/reports/forms/unused'] = array(
    'title' => 'Unused Forms',
    'description' => 'A list of Forms that are not being displayed on this site.',
    'page callback' => 'cu_unused_forms_list',
    'access arguments' => array('view unused forms'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function cu_unused_forms_permission() {
  return array(
    'view unused forms' => array(
      'title' => 'View Unused forms',
      'description' => 'View a list of unused/unreferenced forms.',
    ),
  );
}

/**
 * Page callback for /admin/reports/forms/unused.
 */
function cu_unused_forms_list() {
  drupal_add_css(drupal_get_path('module', 'cu_inactive_users') . '/css/cu-inactive-users.css', array('group' => CSS_DEFAULT));
  $output = [];

  // There are two separate queries because we need to compare nids between the two separate tables.
  // We need nids and submissions AND status of both.
  $forms_count_query = db_query('SELECT * FROM webform');
  $forms_submissions_query = db_query('SELECT * FROM webform_submissions');

  $forms_count = $forms_count_query->fetchAll();
  $forms_submissions = $forms_submissions_query->fetchAll();
  dpm($forms_submissions);

  // Return all form nids (webform) to $form_nids.
  $form_nids = array();
  foreach ($forms_count as $form) {
    $form_nids[] = $form->nid;
  }

  $list = array();

  // Set the default time we want to check access for.
  $time = isset($_GET['time']) ? check_plain($_GET['time']) : 60*60*24*60;

  // Build a readable date we are checking against
  $now = time();
  $since = $now - $time;
  //$since = date('F j, Y', $since);

  // Add some links to allow user to filter by date.
  $time_filters = array();
  $time_options = array(
    '7 Days' => (60*60*24*7),
    '30 Days' => (60*60*24*30),
    '90 Days' => (60*60*24*90),
    '1 Year' => (60*60*24*365),
  );
  $path = current_path();
  global $base_url;
  // If a time is already set, add a default/reset link.
  if ($_GET['time']) {
    $time_filters[] = "<a href=\"$base_url/$path\">Default (60 Days)</a>";
  }
  // Loop through time filter options.
  foreach ($time_options as $label => $interval) {
    if ($_GET['time'] == $interval) {
      $class = 'active-time-filter';
    }
    else {
      $class = '';
    }
    $time_filters[] = "<a href=\"$base_url/$path?time=$interval\" class=\"$class\">$label</a>";
  }

  $forms[] = node_load_multiple($form_nids);

  foreach ($forms as $form) {
    // If time matches current filtered time.
    foreach ($form as $key => $stale_form) {
      $last_submission = '';
      $total_submissions = '';
      $name = l($stale_form->title, 'node/' . $stale_form->nid . '/edit');
      $author = $stale_form->name;

      if ($stale_form->changed < $since) {
        $list[$stale_form->uid] = "$name<br><ul><li>last submission: $last_submission</li><li>total submissions: $total_submissions</li><li><small>$author</small></li></ul>";
      }
    }
  }

  $output['stale_forms']['#prefix'] = '<h2>Have not been used recently</h2>';
  $output['stale_forms']['description']['#markup'] = "<p>The users listed below have not logged in since $since.</p>";
  $output['stale_forms']['filters']['#prefix'] = '<div class="inactive-time-filter">Use the links below to change the date checked.';
  $output['stale_forms']['filters']['#suffix'] = '</div>';
  $output['stale_forms']['filters']['#markup'] = theme('item_list', array('items' => $time_filters, 'attributes' => array('class' => array('inactive-users-time-filters'))));
  $output['stale_forms']['list']['#markup'] = theme('item_list', array('items' => $list, 'attributes' => array('class' => array('bullet-list'))));


  return $output;
}
